"""
Report generator for Gen AI analysis output
Formats analysis into professional Markdown and HTML reports
"""

from typing import Dict, Any, Optional
from datetime import datetime
import json


class ReportGenerator:
    """Generates professional reports from Gen AI analysis"""
    
    def __init__(self, metrics: Dict[str, Any], ai_analysis: str, scenario_name: str = ""):
        """
        Initialize report generator
        
        Args:
            metrics: Aggregated metrics dictionary
            ai_analysis: Gen AI analysis text
            scenario_name: Name of the scenario
        """
        self.metrics = metrics
        self.ai_analysis = ai_analysis
        self.scenario_name = scenario_name or metrics.get('scenario_name', 'Unknown')
        self.timestamp = datetime.now()
    
    def generate_markdown_report(self, filepath: Optional[str] = None) -> str:
        """
        Generate Markdown report
        
        Args:
            filepath: Optional filepath to save report
        
        Returns:
            Markdown report as string
        """
        
        report = f"""# Financial System Simulation Report

**Generated:** {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}  
**Scenario:** {self.scenario_name}  
**Duration:** {self.metrics.get('num_steps', 0)} timesteps

---

## 📊 Key Metrics at a Glance

| Metric | Value |
|--------|-------|
| **Total Banks** | {self.metrics.get('num_banks', 0)} |
| **Total Defaults** | {self.metrics.get('total_defaults', 0)} |
| **Peak Stressed Banks** | {self.metrics.get('total_stressed_max', 0)} |
| **Systemic Risk Index** | {self.metrics.get('systemic_risk_index', 0):.1%} |
| **Max Drawdown** | {self.metrics.get('max_drawdown', 0):.2%} |
| **Final Asset Price** | ${self.metrics.get('final_asset_price', 0):.4f} |
| **Price Volatility** | {self.metrics.get('price_volatility', 0):.4f} |
| **Cascade Potential** | {self.metrics.get('cascade_potential', 0)} banks |
| **Liquidity Stress Events** | {self.metrics.get('liquidity_stress_events', 0)} |

---

## 🤖 AI-Powered Analysis Report

{self._format_ai_analysis()}

---

## 📈 Critical Events

### Default Timeline
| Bank ID | Trigger | Creditors Affected |
|---------|---------|-------------------|
{self._format_defaults_table()}

### Systemic Importance (DebtRank)
| Rank | Bank ID | DebtRank Score |
|------|---------|----------------|
{self._format_debtrank_table()}

---

## 🏦 Per-Bank Outcomes

{self._format_bank_summary()}

---

## 📊 Detailed Metrics

### Market Dynamics
- **Initial Price:** $1.0000
- **Final Price:** ${self.metrics.get('final_asset_price', 0):.4f}
- **Price Change:** {self.metrics.get('price_trend', 0):+.2%}
- **Volatility:** {self.metrics.get('price_volatility', 0):.4f}
- **Max Drawdown:** {self.metrics.get('max_drawdown', 0):.2%}

### Risk Indicators
- **Systemic Risk Index:** {self.metrics.get('systemic_risk_index', 0):.1%}
- **Average DebtRank:** {self.metrics.get('average_debtrank', 0):.4f}
- **Cascade Potential:** {self.metrics.get('cascade_potential', 0)} banks

### Contagion
- **Total Defaults:** {self.metrics.get('total_defaults', 0)}
- **Cascading Events:** {self.metrics.get('total_contagion_events', 0)}

---

## ⚙️ Simulation Configuration

- **Scenario Name:** {self.scenario_name}
- **Number of Banks:** {self.metrics.get('num_banks', 0)}
- **Simulation Steps:** {self.metrics.get('num_steps', 0)}
- **Timestamp:** {self.metrics.get('timestamp', 'N/A')}

---

## 📎 Raw Data

<details>
<summary>Click to expand raw metrics JSON</summary>

```json
{json.dumps({k: v for k, v in self.metrics.items() if not isinstance(v, (list, dict)) or k in ['default_events', 'top_10_debtrank']}, indent=2, default=str)}
```

</details>

---

*Report generated by FinSim-MAPPO Gen AI Analysis System  
Powered by Featherless API with Kimi-K2-Thinking Model*
"""
        
        if filepath:
            with open(filepath, 'w') as f:
                f.write(report)
            print(f"✅ Markdown report saved to {filepath}")
        
        return report
    
    def generate_html_report(self, filepath: Optional[str] = None) -> str:
        """
        Generate HTML report with styling
        
        Args:
            filepath: Optional filepath to save report
        
        Returns:
            HTML report as string
        """
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Financial System Simulation Report</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #333;
            padding: 20px;
            min-height: 100vh;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            overflow: hidden;
        }}
        header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }}
        header h1 {{
            font-size: 2.5em;
            margin-bottom: 10px;
        }}
        header p {{
            font-size: 1.1em;
            opacity: 0.9;
        }}
        .content {{
            padding: 40px;
        }}
        h2 {{
            color: #667eea;
            margin: 30px 0 15px 0;
            padding-bottom: 10px;
            border-bottom: 2px solid #667eea;
        }}
        h3 {{
            color: #764ba2;
            margin: 20px 0 10px 0;
        }}
        .metrics-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }}
        .metric-card {{
            background: #f8f9fa;
            border-left: 4px solid #667eea;
            padding: 20px;
            border-radius: 8px;
        }}
        .metric-label {{
            font-size: 0.9em;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 1px;
        }}
        .metric-value {{
            font-size: 1.8em;
            font-weight: bold;
            color: #667eea;
            margin-top: 5px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }}
        th {{
            background: #f0f2f5;
            padding: 12px;
            text-align: left;
            font-weight: 600;
            color: #333;
            border-bottom: 2px solid #667eea;
        }}
        td {{
            padding: 12px;
            border-bottom: 1px solid #e0e0e0;
        }}
        tr:hover {{
            background: #f8f9fa;
        }}
        .analysis-section {{
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
            line-height: 1.8;
        }}
        .status-active {{
            color: #28a745;
            font-weight: bold;
        }}
        .status-stressed {{
            color: #ffc107;
            font-weight: bold;
        }}
        .status-defaulted {{
            color: #dc3545;
            font-weight: bold;
        }}
        code {{
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: 'Monaco', 'Courier New', monospace;
        }}
        footer {{
            background: #f8f9fa;
            padding: 20px;
            text-align: center;
            color: #666;
            font-size: 0.9em;
            border-top: 1px solid #e0e0e0;
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>💰 Financial System Simulation Report</h1>
            <p>Network-Based Game-Theoretic Modeling of Financial Infrastructure</p>
            <p style="font-size: 0.9em; margin-top: 10px;">{self.timestamp.strftime('%B %d, %Y at %H:%M:%S')}</p>
        </header>
        
        <div class="content">
            <h2>📊 Scenario Overview</h2>
            <p><strong>Scenario:</strong> {self.scenario_name}</p>
            <p><strong>Duration:</strong> {self.metrics.get('num_steps', 0)} timesteps across {self.metrics.get('num_banks', 0)} banks</p>
            
            <h2>🎯 Critical Metrics</h2>
            <div class="metrics-grid">
                <div class="metric-card">
                    <div class="metric-label">Total Defaults</div>
                    <div class="metric-value">{self.metrics.get('total_defaults', 0)}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Peak Stressed</div>
                    <div class="metric-value">{self.metrics.get('total_stressed_max', 0)}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Systemic Risk</div>
                    <div class="metric-value">{self.metrics.get('systemic_risk_index', 0):.1%}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Max Drawdown</div>
                    <div class="metric-value">{self.metrics.get('max_drawdown', 0):.2%}</div>
                </div>
            </div>
            
            <h2>🤖 AI Analysis</h2>
            <div class="analysis-section">
                {self._html_escape(self.ai_analysis)[:2000]}...
            </div>
            
            <h2>📈 Default Events</h2>
            <table>
                <thead>
                    <tr>
                        <th>Bank ID</th>
                        <th>Trigger</th>
                        <th>Creditors Affected</th>
                    </tr>
                </thead>
                <tbody>
                    {self._format_defaults_html()}
                </tbody>
            </table>
            
            <h2>🏆 Systemic Importance (DebtRank)</h2>
            <table>
                <thead>
                    <tr>
                        <th>Rank</th>
                        <th>Bank ID</th>
                        <th>DebtRank Score</th>
                    </tr>
                </thead>
                <tbody>
                    {self._format_debtrank_html()}
                </tbody>
            </table>
        </div>
        
        <footer>
            <p>Generated by FinSim-MAPPO Gen AI Analysis System</p>
            <p>Powered by Featherless API with Kimi-K2-Thinking Model</p>
        </footer>
    </div>
</body>
</html>"""
        
        if filepath:
            with open(filepath, 'w') as f:
                f.write(html)
            print(f"✅ HTML report saved to {filepath}")
        
        return html
    
    def _format_ai_analysis(self) -> str:
        """Format AI analysis for Markdown"""
        
        # Split into sections if available
        text = self.ai_analysis
        if len(text) > 5000:
            return text[:5000] + "\n\n... [Full analysis continues] ..."
        return text
    
    def _format_defaults_table(self) -> str:
        """Format defaults as Markdown table"""
        
        rows = []
        for event in self.metrics.get('default_events', [])[:10]:
            rows.append(
                f"| {event.get('bank_id', 'N/A')} | "
                f"{event.get('trigger', 'unknown')} | "
                f"{event.get('creditors_affected', 0)} |"
            )
        
        return '\n'.join(rows) if rows else "| - | - | - |"
    
    def _format_debtrank_table(self) -> str:
        """Format DebtRank as Markdown table"""
        
        rows = []
        for rank, (bank_id, score) in enumerate(
            sorted(
                self.metrics.get('top_10_debtrank', {}).items(),
                key=lambda x: x[1],
                reverse=True
            ),
            1
        ):
            rows.append(f"| {rank} | {bank_id} | {score:.4f} |")
        
        return '\n'.join(rows) if rows else "| - | - | - |"
    
    def _format_bank_summary(self) -> str:
        """Format per-bank summary"""
        
        outcomes = self.metrics.get('bank_outcomes', {})
        
        if not outcomes:
            return "No bank outcome data available"
        
        # Count statuses
        active = sum(1 for b in outcomes.values() if b.get('final_status') == 'active')
        stressed = sum(1 for b in outcomes.values() if b.get('final_status') == 'stressed')
        defaulted = sum(1 for b in outcomes.values() if b.get('final_status') == 'defaulted')
        
        md = f"""
**Summary:**
- 🟢 Active Banks: {active}
- 🟡 Stressed Banks: {stressed}
- 🔴 Defaulted Banks: {defaulted}

**Top 5 Banks by Final Equity:**

| Bank ID | Status | Equity | Capital Ratio |
|---------|--------|--------|---------------|
"""
        
        for bank_id, outcome in sorted(
            outcomes.items(),
            key=lambda x: x[1].get('final_equity', 0),
            reverse=True
        )[:5]:
            status_emoji = "🟢" if outcome['final_status'] == "active" else \
                          "🟡" if outcome['final_status'] == "stressed" else "🔴"
            
            md += (f"| {bank_id} | {status_emoji} {outcome['final_status']} | "
                   f"${outcome['final_equity']:.2f}M | "
                   f"{outcome['final_capital_ratio']:.2%} |\n")
        
        return md
    
    def _format_defaults_html(self) -> str:
        """Format defaults as HTML table rows"""
        
        rows = ""
        for event in self.metrics.get('default_events', [])[:10]:
            rows += f"""
            <tr>
                <td>{event.get('bank_id', 'N/A')}</td>
                <td>{event.get('trigger', 'unknown')}</td>
                <td>{event.get('creditors_affected', 0)}</td>
            </tr>"""
        
        return rows if rows else "<tr><td colspan='3'>No default events</td></tr>"
    
    def _format_debtrank_html(self) -> str:
        """Format DebtRank as HTML table rows"""
        
        rows = ""
        for rank, (bank_id, score) in enumerate(
            sorted(
                self.metrics.get('top_10_debtrank', {}).items(),
                key=lambda x: x[1],
                reverse=True
            ),
            1
        ):
            rows += f"""
            <tr>
                <td>{rank}</td>
                <td>{bank_id}</td>
                <td>{score:.4f}</td>
            </tr>"""
        
        return rows if rows else "<tr><td colspan='3'>No DebtRank data</td></tr>"
    
    def _html_escape(self, text: str) -> str:
        """Escape HTML special characters"""
        
        return (text
                .replace('&', '&amp;')
                .replace('<', '&lt;')
                .replace('>', '&gt;')
                .replace('"', '&quot;')
                .replace("'", '&#39;'))
